wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.15
    cli_version: 0.19.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1767613058
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 14
      - 23
      - 37
      - 61
      4: 3.10.15
      5: 0.19.1
      8:
      - 5
      13: linux-x86_64
lr:
  desc: null
  value: 0.0005
seed:
  desc: null
  value: 1
app_num:
  desc: null
  value: 2
model:
  desc: null
  value: tgat
emb:
  desc: null
  value: attn
optimizer:
  desc: null
  value: adam
epochs:
  desc: null
  value: 100
early_stop:
  desc: null
  value: 1
patience:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 16
latent_dim:
  desc: null
  value: 32
wandb:
  desc: null
  value: 1
save_model:
  desc: null
  value: 1
dataset_name:
  desc: null
  value: CollegeMsg
source_id:
  desc: null
  value: 0
